### ISSUE TITLE
Integrate existing server GraphQL query in client - TODO

### ISSUE THREAD

**Issue by smitbarmase** [smitbarmase/zenmode#6]
- [x] Show invitations
- [x] Invite Member/Admin
- [x] Accept Invite Dialog
- [ ] Leave Pod
- [ ] Remove Member/Admin from Pod
- [x] Show all members and admins
- [x] Add user to tasks

**Comment by smitbarmase** [comment]
Additional issues created for the remaining tasks.
